(function(){
'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const list=$('booksList'),status=$('booksStatus'),search=$('bookSearch'),era=$('bookEra'),category=$('bookCategory');let timer=null,serial=0;
function menu(){const m=$('booksSideMenu'),o=$('booksMenuOverlay');const open=()=>{m.classList.add('open');o.classList.add('active');m.setAttribute('aria-hidden','false')};const close=()=>{m.classList.remove('open');o.classList.remove('active');m.setAttribute('aria-hidden','true')};$('booksMenuButton')?.addEventListener('click',open);$('booksCloseMenu')?.addEventListener('click',close);o?.addEventListener('click',close)}
function clean(v){return String(v||'').trim()}
function row(b){const meta=[b.author,b.literary_category,b.era].filter(Boolean).map(x=>`<span>${esc(x)}</span>`).join('');const cover=b.cover_url?`<img class="book-cover" src="${esc(b.cover_url)}" alt="غلاف ${esc(b.title)}" loading="lazy">`:'';return `<article class="book-row${b.cover_url?'':' no-cover'}" tabindex="0" role="button" data-book-id="${esc(b.id)}">${cover}<div class="book-row-body"><h2>${esc(b.title||'بدون عنوان')}</h2><div class="book-row-meta">${meta}</div>${b.description?`<p class="book-row-desc">${esc(b.description)}</p>`:''}</div></article>`}
async function filterOptions(){try{const {data,error}=await supabaseClient.from('books').select('era,literary_category').limit(1000);if(error)throw error;const eras=[...new Set((data||[]).map(x=>clean(x.era)).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ar'));const cats=[...new Set((data||[]).map(x=>clean(x.literary_category)).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ar'));era.innerHTML='<option value="">جميع العصور</option>'+eras.map(x=>`<option>${esc(x)}</option>`).join('');category.innerHTML='<option value="">جميع الفئات الأدبية</option>'+cats.map(x=>`<option>${esc(x)}</option>`).join('')}catch(e){console.warn(e)}}
async function load(){const s=++serial;status.hidden=true;status.textContent='';list.innerHTML='';let q=supabaseClient.from('books').select('*').order('is_featured',{ascending:false}).order('created_at',{ascending:false}).limit(120);const term=clean(search.value);if(term)q=q.or(`title.ilike.%${term.replace(/[,()]/g,' ')}%,author.ilike.%${term.replace(/[,()]/g,' ')}%`);if(era.value)q=q.eq('era',era.value);if(category.value)q=q.eq('literary_category',category.value);try{const {data,error}=await q;if(error)throw error;if(s!==serial)return;const rows=data||[];status.hidden=!!rows.length;status.textContent=rows.length?'':'لا توجد عناصر مطابقة.';list.innerHTML=rows.map(row).join('');list.querySelectorAll('.book-row').forEach((el,i)=>{const b=rows[i];const open=()=>viewer.open(b);el.addEventListener('click',open);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}})})}catch(e){console.error(e);status.hidden=false;status.textContent='لا توجد عناصر مطابقة.'}}
search?.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(load,260)});era?.addEventListener('change',load);category?.addEventListener('change',load);
const viewer=(function(){let pdf=null,page=1,scale=1,renderTask=null,startX=null;const root=$('bookViewer'),canvas=$('bookCanvas'),wrap=$('bookCanvasWrap'),stage=$('bookStage'),msg=$('bookViewerMessage'),ctx=canvas.getContext('2d');async function pdfjs(){if(window.pdfjsLib)return window.pdfjsLib;try{const m=await import('https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.min.mjs');m.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.worker.min.mjs';return m}catch(e){throw new Error('تعذر تحميل قارئ PDF')}}async function render(){if(!pdf)return;try{renderTask?.cancel?.()}catch{}const p=await pdf.getPage(page);const viewport=p.getViewport({scale:scale*Math.min(1.8,Math.max(.55,(stage.clientWidth-28)/(p.getViewport({scale:1}).width||800)))});canvas.width=Math.floor(viewport.width);canvas.height=Math.floor(viewport.height);canvas.style.width=viewport.width+'px';canvas.style.height=viewport.height+'px';wrap.hidden=false;msg.hidden=true;renderTask=p.render({canvasContext:ctx,viewport});try{await renderTask.promise}catch(e){if(e?.name!=='RenderingCancelledException')throw e}$('bookPageCount').textContent=`${page} / ${pdf.numPages}`;$('bookZoomLabel').textContent=Math.round(scale*100)+'%';stage.scrollTop=0;stage.scrollLeft=0}
async function open(book){root.classList.add('open');root.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';$('bookViewerTitle').textContent=book.title||'الكتاب';msg.hidden=false;msg.textContent='جاري فتح الكتاب...';wrap.hidden=true;page=1;scale=1;pdf=null;try{const lib=await pdfjs();pdf=await lib.getDocument({url:book.file_url,withCredentials:false}).promise;await render()}catch(e){console.error(e);msg.hidden=false;wrap.hidden=true;msg.textContent='تعذر فتح ملف الكتاب. تأكد أن الرابط مباشر لملف PDF ومتاح للعامة.'}}
function close(){root.classList.remove('open');root.setAttribute('aria-hidden','true');document.body.style.overflow='';pdf=null;try{renderTask?.cancel?.()}catch{}}
async function prev(){if(pdf&&page>1){page--;await render()}}async function next(){if(pdf&&page<pdf.numPages){page++;await render()}}async function zoom(delta){scale=Math.max(.6,Math.min(2.6,scale+delta));await render()}
$('bookClose')?.addEventListener('click',close);$('bookPrev')?.addEventListener('click',prev);$('bookBottomPrev')?.addEventListener('click',prev);$('bookNext')?.addEventListener('click',next);$('bookBottomNext')?.addEventListener('click',next);$('bookZoomOut')?.addEventListener('click',()=>zoom(-.15));$('bookZoomIn')?.addEventListener('click',()=>zoom(.15));$('bookFullscreen')?.addEventListener('click',async()=>{try{if(!document.fullscreenElement)await root.requestFullscreen();else await document.exitFullscreen()}catch{}});document.addEventListener('keydown',e=>{if(!root.classList.contains('open'))return;if(e.key==='Escape')close();if(e.key==='ArrowRight')prev();if(e.key==='ArrowLeft')next();if(e.key==='+')zoom(.15);if(e.key==='-')zoom(-.15)});stage?.addEventListener('touchstart',e=>{startX=e.touches?.[0]?.clientX??null},{passive:true});stage?.addEventListener('touchend',e=>{if(startX===null)return;const end=e.changedTouches?.[0]?.clientX??startX,d=end-startX;startX=null;if(Math.abs(d)>70){if(d>0)next();else prev()}},{passive:true});stage?.addEventListener('dblclick',()=>zoom(.2));return{open,close}})();
menu();filterOptions();load();
})();
