-- القافية: إصلاح نهائي للإحصائيات + البلد + الملف الشخصي. شغّله مرة واحدة في Supabase SQL Editor.
begin;

alter table public.profiles add column if not exists country_code text;
alter table public.profiles drop constraint if exists profiles_country_code_check;
alter table public.profiles add constraint profiles_country_code_check check(country_code is null or (country_code ~ '^[A-Z]{2}$' and country_code <> 'IL'));
alter table public.profiles enable row level security;
drop policy if exists "qafiyah_profile_self_select" on public.profiles;
create policy "qafiyah_profile_self_select" on public.profiles for select to authenticated using(id=auth.uid());
drop policy if exists "qafiyah_profile_self_insert" on public.profiles;
create policy "qafiyah_profile_self_insert" on public.profiles for insert to authenticated with check(id=auth.uid());
drop policy if exists "qafiyah_profile_self_update" on public.profiles;
create policy "qafiyah_profile_self_update" on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());

create or replace function public.qafiyah_handle_auth_user_profile() returns trigger language plpgsql security definer set search_path=public,auth as $$
begin
 insert into public.profiles(id,first_name,last_name,birth_day,birth_month,birth_year,gender,phone,country_code)
 values(new.id,nullif(btrim(coalesce(new.raw_user_meta_data->>'first_name','')),''),nullif(btrim(coalesce(new.raw_user_meta_data->>'last_name','')),''),case when coalesce(new.raw_user_meta_data->>'birth_day','')~'^\d+$' then (new.raw_user_meta_data->>'birth_day')::int end,case when coalesce(new.raw_user_meta_data->>'birth_month','')~'^\d+$' then (new.raw_user_meta_data->>'birth_month')::int end,case when coalesce(new.raw_user_meta_data->>'birth_year','')~'^\d+$' then (new.raw_user_meta_data->>'birth_year')::int end,nullif(btrim(coalesce(new.raw_user_meta_data->>'gender','')),''),new.phone,case when upper(coalesce(new.raw_user_meta_data->>'country_code',''))~'^[A-Z]{2}$' and upper(new.raw_user_meta_data->>'country_code')<>'IL' then upper(new.raw_user_meta_data->>'country_code') end)
 on conflict(id) do update set phone=coalesce(excluded.phone,public.profiles.phone),country_code=coalesce(excluded.country_code,public.profiles.country_code);
 return new;
end $$;
drop trigger if exists qafiyah_auth_user_profile_trg on auth.users;
create trigger qafiyah_auth_user_profile_trg after insert or update of phone,raw_user_meta_data on auth.users for each row execute function public.qafiyah_handle_auth_user_profile();

create table if not exists public.qafiyah_visits(id bigint generated by default as identity primary key,device_id text not null,user_id uuid references auth.users(id) on delete set null,visited_at timestamptz not null default now());
create table if not exists public.qafiyah_active_sessions(device_id text primary key,user_id uuid references auth.users(id) on delete set null,last_seen timestamptz not null default now());
create table if not exists public.qafiyah_seen_accounts(user_id uuid primary key references auth.users(id) on delete cascade,first_seen timestamptz not null default now(),last_seen timestamptz not null default now());
create index if not exists qafiyah_visits_time_idx on public.qafiyah_visits(visited_at desc);
create index if not exists qafiyah_visits_device_idx on public.qafiyah_visits(device_id);
create index if not exists qafiyah_active_last_seen_idx on public.qafiyah_active_sessions(last_seen desc);
alter table public.qafiyah_visits enable row level security;alter table public.qafiyah_active_sessions enable row level security;alter table public.qafiyah_seen_accounts enable row level security;

create or replace function public.qafiyah_track_visit(p_device_id text,p_record_visit boolean default false) returns void language plpgsql security definer set search_path=public,auth as $$
declare d text:=left(btrim(coalesce(p_device_id,'')),120);u uuid:=auth.uid();begin
 if length(d)<12 then return;end if;
 if p_record_visit then insert into public.qafiyah_visits(device_id,user_id) values(d,u);end if;
 if u is not null then insert into public.qafiyah_seen_accounts(user_id,first_seen,last_seen) values(u,now(),now()) on conflict(user_id) do update set last_seen=now();end if;
 insert into public.qafiyah_active_sessions(device_id,user_id,last_seen) values(d,u,now()) on conflict(device_id) do update set user_id=excluded.user_id,last_seen=now();
end $$;
revoke all on function public.qafiyah_track_visit(text,boolean) from public;grant execute on function public.qafiyah_track_visit(text,boolean) to anon,authenticated;

create or replace function public.qafiyah_admin_dashboard_summary() returns jsonb language plpgsql stable security definer set search_path=public,auth as $$
declare r text;result jsonb;begin
 select role into r from public.admin_users where user_id=auth.uid() and is_active=true limit 1;if r not in('owner','manager') then raise exception 'not authorized';end if;
 select jsonb_build_object(
 'poets',(select count(*) from public.poets),'poems',(select count(*) from public.poems),'articles',(select count(*) from public.articles),'meters',(select count(*) from public.meters),'rhymes',(select count(*) from public.rhymes),'videos',(select count(*) from public.videos),'books',(select count(*) from public.books),'users',case when r='owner' then(select count(*) from auth.users)else 0 end,
 'featured_poets',(select count(*) from public.poets where is_featured=true),'featured_poems',(select count(*) from public.poems where is_featured=true),'featured_articles',(select count(*) from public.articles where is_featured=true),'featured_meters',(select count(*) from public.meters where is_featured=true),'featured_rhymes',(select count(*) from public.rhymes where is_featured=true),'featured_videos',(select count(*) from public.videos where is_featured=true),
 'total_visits',(select count(*) from public.qafiyah_visits),'unique_devices',(select count(distinct device_id) from public.qafiyah_visits),'unique_accounts',(select count(*) from public.qafiyah_seen_accounts),'active_now',(select count(*) from public.qafiyah_active_sessions where last_seen>=now()-interval '3 minutes'),'today',(select count(*) from public.qafiyah_visits where visited_at>=date_trunc('day',now())),'last_7_days',(select count(*) from public.qafiyah_visits where visited_at>=now()-interval '7 days'),'last_30_days',(select count(*) from public.qafiyah_visits where visited_at>=now()-interval '30 days'),'this_month',(select count(*) from public.qafiyah_visits where visited_at>=date_trunc('month',now())),'last_365_days',(select count(*) from public.qafiyah_visits where visited_at>=now()-interval '365 days'),'this_year',(select count(*) from public.qafiyah_visits where visited_at>=date_trunc('year',now())),
 'years',coalesce((select jsonb_agg(jsonb_build_object('year',y,'visits',c) order by y)from(select extract(year from visited_at)::int y,count(*)::bigint c from public.qafiyah_visits group by 1)s),'[]'::jsonb),
 'months',coalesce((select jsonb_agg(jsonb_build_object('year',y,'month',m,'visits',c) order by y,m)from(select extract(year from visited_at)::int y,extract(month from visited_at)::int m,count(*)::bigint c from public.qafiyah_visits group by 1,2)s),'[]'::jsonb)) into result;return result;
end $$;
revoke all on function public.qafiyah_admin_dashboard_summary() from public,anon;grant execute on function public.qafiyah_admin_dashboard_summary() to authenticated;


-- عداد المستخدمين للمالك فقط؛ يستخدمه التحديث التلقائي في لوحة الإدارة.
create or replace function public.get_users_count() returns bigint
language plpgsql security definer set search_path=public,auth as $$
declare r text;
begin
  select role into r from public.admin_users where user_id=auth.uid() and is_active=true limit 1;
  if r <> 'owner' then raise exception 'not authorized'; end if;
  return (select count(*)::bigint from auth.users);
end $$;
revoke all on function public.get_users_count() from public,anon;
grant execute on function public.get_users_count() to authenticated;
create or replace function public.qafiyah_analytics_summary() returns jsonb language plpgsql stable security definer set search_path=public,auth as $$begin return public.qafiyah_admin_dashboard_summary();end$$;
revoke all on function public.qafiyah_analytics_summary() from public,anon;grant execute on function public.qafiyah_analytics_summary() to authenticated;
delete from public.qafiyah_active_sessions where last_seen<now()-interval '2 days';
commit;
-- فحص آمن داخل SQL Editor (لا يعتمد على جلسة مستخدم الموقع)
select
  (select count(*) from public.poets) as poets,
  (select count(*) from public.poems) as poems,
  (select count(*) from public.articles) as articles,
  (select count(*) from public.qafiyah_visits) as visits;
